### ISSUE TITLE
Better Chat Mute - reason command parameter

### ISSUE THREAD

**Issue by TheDoc777** [umods/BetterChatMute#1]
Why did you add CASE 3: to the /mute command?

It's not spelled out in the description:

mute <player|steamid> -- Mutes player permanently
mute <player|steamid> [time: 1d1h1m1s] -- Mutes player temporarily
unmute <player|steamid> -- Unmutes player

So you need to give a reason for mute? Can you please make that optional?

Thanks

**Comment by LaserHydra** [comment]
Yes I forgot to add that to the description, thank you for the heads up.
It is optional, you can just type empty quotes for the reason ("").
Although, I see what you mean.

I might have to split it up into two seperate commands being /mute and /timemute
